name: Run Cucumber Test

on:
  push:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "22"
          cache: maven
          distribution: "temurin"
      - uses: browser-actions/setup-chrome@latest
      - run: mvn clean test
      - name: Generate Allure Report
        run: mvn allure:report
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
